### ISSUE TITLE
Mount Map Component on Dashboard

### ISSUE THREAD

**Issue by KaseKreative** [KaseKreative/GymBoApp#23]

**Comment by jeffreymendez1993** [comment]
https://github.com/KaseKreative/GymBoApp/commit/99e5fde6a98bda7cc3e34a7d7c444725d79216d0

**Comment by jeffreymendez1993** [comment]
https://github.com/KaseKreative/GymBoApp/commit/53a2c9399dc102e160b366d22ca9711d0bb0358a
